import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const [source, baseline] = process.argv.slice(2).map(p=>path.resolve(p));
if (!source || !baseline || source === baseline) throw new Error('Usage: generate-data.mjs STAGED_SOURCE CLEAN_UPSTREAM');
const {applyRhineData,validateRhineData}=await import(pathToFileURL(path.join(source,'tools/rhine-data.mjs')));
const names=['chess','bonds','garrisons','tokens','effects','config','items'];
const files=Object.fromEntries(names.map(n=>[n,JSON.parse(fs.readFileSync(path.join(source,'data',n+'.json'),'utf8'))]));
await applyRhineData(files);
const errors=validateRhineData(files);
if(errors.length)throw new Error(JSON.stringify(errors));
for(const n of names)fs.writeFileSync(path.join(source,'data',n+'.json'),JSON.stringify(files[n]));
const vanilla=path.join(source,'data/vanilla');fs.mkdirSync(vanilla,{recursive:true});
fs.cpSync(path.join(baseline,'data'), vanilla, {recursive:true});
console.log('Rhine generated from pinned upstream; complete vanilla snapshot copied.');
